version: '2'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    #command: bash -c "npm install && npm start"
    command: bash -c "npm install && npm run watch"
    ports:
      - "3000:3000"

